[package]
name = "the_whisper_api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
rsa = "0.9.8"
serde = { version = "1.0.219", features = ["derive"] }
base64 = "0.22.1"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
cosmian_crypto_core = "10.0.1"
sha2 = "0.10.8"
rand = "0.9.1"
rand_core = "0.9.3"
